dj4e/autos/urls.py
from django.urls import path, reverse
from . import views

from django.views.generic import RedirectView

urlpatterns = [
    path('', views.AutoIndexView.as_view(), name='autos-index'),
    path('autos/', views.AutoListView.as_view(), name='autos'),
    path('autos/<int:pk>', views.AutoDetailView.as_view(), name='auto'),
    path('autos/<int:pk>/update/', views.AutoUpdate.as_view(), name='auto-update'),
    path('autos/<int:pk>/delete/', views.AutoDelete.as_view(), name='auto-delete'),
    path('auto/create/', views.AutoCreate.as_view(), name='auto-create'),

    path('makes/', views.MakeListView.as_view(), name='makes'),
    path('makes/<int:pk>', views.MakeDetailView.as_view(), name='make'),
    path('makes/<int:pk>/update/', views.MakeUpdate.as_view(), name='make-update'),
    path('makes/<int:pk>/delete/', views.MakeDelete.as_view(), name='make-delete'),
    path('make/create/', views.MakeCreate.as_view(), name='make-create'),
]

dj4e/cats/urls.py
from django.urls import path, reverse
from . import views

from django.views.generic import RedirectView

urlpatterns = [
    path('', views.CatIndexView.as_view(), name='cats-index'),

    path('cats/', views.CatListView.as_view(), name='cats'),
    path('cats/<int:pk>', views.CatDetailView.as_view(), name='cat'),
    path('cats/<int:pk>/update/', views.CatUpdate.as_view(), name='cat-update'),
    path('cats/<int:pk>/delete/', views.CatDelete.as_view(), name='cat-delete'),
    path('cat/create/', views.CatCreate.as_view(), name='cat-create'),

    path('breeds/', views.BreedListView.as_view(), name='breeds'),
    path('breeds/<int:pk>', views.BreedDetailView.as_view(), name='breed'),
    path('breeds/<int:pk>/update/', views.BreedUpdate.as_view(), name='breed-update'),
    path('breeds/<int:pk>/delete/', views.BreedDelete.as_view(), name='breed-delete'),
    path('breed/create/', views.BreedCreate.as_view(), name='breed-create'),
]

dj4e/dj4e/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('autos/', include('autos.urls')),
    path('cats/', include('cats.urls')),
    path('citys/', include('citys.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('home.urls'))
]

# New lines below to serve static files in debug mode
import os
from django.urls import re_path
from django.views.static import serve
from django.conf import settings

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

if settings.DEBUG:
    urlpatterns += [
        re_path(r'^static/(?P<path>.*)$', serve, {
            'document_root': os.path.join(BASE_DIR, 'catalog/static'),
        }),
    ]

dj4e/autos/models.py
from django.db import models

from django.urls import reverse

# Create your models here.
class Auto(models.Model):
    nickname = models.CharField(max_length=100)
    make = models.ForeignKey('Make', on_delete=models.SET_NULL, null=True)
    mileage = models.PositiveIntegerField(default=0)
    comments = models.CharField(max_length=300, null=True)

    class Meta:
        ordering = ['make']
        permissions = (
            ('AutoFullAccess', 'Full access: can do CRUD on auto'),
            ('AutoReadOnly', 'Read only: can read all auto data, but not modifying them'),
        )

    def get_absolute_url(self):
        return reverse('auto', args=[str(self.id)])
    
    def __str__(self):
        return self.nickname

class Make(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        ordering = ['name']
        permissions = (
            ('MakeFullAccess', 'Full access: can do CRUD on make'),
            ('MakeReadOnly', 'Read only: can read all make data, but not modifying them'),
        )

    def get_absolute_url(self):
        return reverse('make', args=[str(self.id)])
    
    def __str__(self):
        return self.name

dj4e/autos/views.py
from django.shortcuts import render

from django.urls import reverse, reverse_lazy

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import permission_required

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import TemplateView
from django.views import generic

from autos.models import Auto, Make

class AutoIndexView(LoginRequiredMixin, TemplateView):
    template_name = 'autos/index.html'

# Create your views here.
class AutoListView(LoginRequiredMixin, generic.ListView):
    model = Auto
    paginate_by = 99

    # template_name = 'catalog/book_list.html' # by default will find this template
    # context_object_name = 'books' # by default will use `book_list` as variable name in template (<model>_list)

    def get_queryset(self):
        # import ipdb; ipdb.set_trace()
        query_result = Auto.objects.all().order_by('pk')
        return query_result # this is the default behavior; you can change this to filter 
    
    def get_context_data(self, *args, object_list=None, **kwargs):
        context = super().get_context_data(*args, object_list=object_list, **kwargs)
        # add new keys to context here
        return context

class AutoDetailView(LoginRequiredMixin, generic.DetailView):
    model = Auto

class AutoCreate(PermissionRequiredMixin, LoginRequiredMixin, CreateView):
    permission_required = ('autos.AutoFullAccess',)
    model = Auto
    fields = '__all__'
    initial = {}

class AutoUpdate(PermissionRequiredMixin, LoginRequiredMixin, UpdateView):
    permission_required = ('autos.AutoFullAccess',)
    model = Auto
    fields = [
        'nickname', 
        'make',
        'mileage',
        'comments',
    ]

class AutoDelete(PermissionRequiredMixin, LoginRequiredMixin, DeleteView):
    permission_required = ('autos.AutoFullAccess',)
    model = Auto
    success_url = reverse_lazy('autos')

class MakeListView(LoginRequiredMixin, generic.ListView):
    model = Make
    paginate_by = 99

class MakeDetailView(LoginRequiredMixin, generic.DetailView):
    model = Make

class MakeCreate(PermissionRequiredMixin, LoginRequiredMixin, CreateView):
    permission_required = ('autos.MakeFullAccess',)
    model = Make
    fields = '__all__'
    initial = {}

class MakeUpdate(PermissionRequiredMixin, LoginRequiredMixin, UpdateView):
    permission_required = ('autos.MakeFullAccess',)
    model = Make
    fields = [
        'name',
    ]

class MakeDelete(PermissionRequiredMixin, LoginRequiredMixin, DeleteView):
    permission_required = ('autos.MakeFullAccess',)
    model = Make
    success_url = reverse_lazy('makes')

dj4e/autos/templates/autos/auto_confirm_delete.html
{% extends "base-auto.html" %}

{% block appContent %}

<h1>Delete Auto</h1>

<p>Are you sure you want to delete the auto: {{ auto }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

dj4e/autos/templates/autos/auto_detail.html
{% extends "base-auto.html" %}

{% block appContent %}
  <h1>Model Name: {{ auto.nickname }}</h1>
  <p>
      <a href="{% url 'auto-update' pk=auto.id %}">Update</a> | <a href="{% url 'auto-delete' pk=auto.id %}">Delete</a>
  </p>
  <p><strong>Make:</strong> <a href="{{ auto.make.get_absolute_url }}">{{ auto.make }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Mile Age:</strong> {{ auto.mileage }}</p>
  <p><strong>Comments:</strong> {{ auto.comments }}</p>
{% endblock %}

dj4e/autos/templates/autos/auto_form.html
{% extends "base-auto.html" %}

{% block appContent %}
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
</form>
{% endblock %}

dj4e/autos/templates/autos/auto_list.html
{% extends "base-auto.html" %}

{% block appContent %}
  <h1>Auto List</h1>
  <p>
      <a href="{% url 'auto-create' %}">Add an auto</a>
  </p>
  {% if auto_list %}
  <ul>
    {% for auto in auto_list %}
      <li>
        <a href="{{ auto.get_absolute_url }}">{{ auto.nickname }}</a> ({{auto.make}}) (
            <a href="{% url 'auto-update' pk=auto.id %}">Update</a> |
            <a href="{% url 'auto-delete' pk=auto.id %}">delete</a>
        )
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no autos.</p>
  {% endif %}       
{% endblock %}

dj4e/autos/templates/autos/index.html
{% extends "base-auto.html" %}

{% block appContent %}
<h1>Welcome to the automotive industry</h1>
<p>
    Feeling creative? You can:
    <ul>
        <li>
            <a href="{% url 'auto-create' %}">Add an auto</a>
        </li>
        <li>
            <a href="{% url 'make-create' %}">Add a make</a>
        </li>
    </ul>
    Or, view at our rich database.
</p>
{% endblock %}

dj4e/autos/templates/autos/make_confirm_delete.html
{% extends "base-auto.html" %}

{% block appContent %}

<h1>Delete Make</h1>

<p>Are you sure you want to delete the make: {{ make }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

dj4e/autos/templates/autos/make_detail.html
{% extends "base-auto.html" %}

{% block appContent %}
<h1>Make Name: {{ make.name }}</h1>
{% if make.auto_set.all %}
<h2>Models:</h2>
<p>
    <ul>
        {% for auto in make.auto_set.all %}
        <li>
            <a href="{% url 'auto' pk=auto.id %}">{{auto.nickname}}</a>
        </li>
        {% endfor %}
    </ul>
</p>
{% else %}
<p>
    No this make's auto yet.
</p>
{% endif %}
{% endblock %}

dj4e/autos/templates/autos/make_form.html
{% extends "base-auto.html" %}

{% block appContent %}
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
</form>
{% endblock %}

dj4e/autos/templates/autos/make_list.html
{% extends "base-auto.html" %}

{% block appContent %}
  <h1>Make List</h1>
  <p>
      <a href="{% url 'make-create' %}">Add a make</a>
  </p>
  {% if make_list %}
  <ul>
    {% for make in make_list %}
      <li>
        <a href="{{ make.get_absolute_url }}">{{ make.name }}</a> (
            <a href="{% url 'make-update' pk=make.id %}">Update</a> |
            <a href="{% url 'make-delete' pk=make.id %}">delete</a>
        )
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no makes.</p>
  {% endif %}
{% endblock %}